### ISSUE TITLE
Latest mystcraft crashes on forge 1307. (can't update)

### ISSUE THREAD

**Issue by seantherobonaut** [XCompWiz/Mystcraft-Issues#62] opened 2015-04-07 07:10 UTC
I can't update the the latest version of forge because the latest version of cauldron only has forge 1307. 

I tried using an older version of mystcraft 0.11.0.00 which does load, but as soon as I create a new age server-side, extreme lag occurs on any system I try. This usually pulls it to 5 tps. If I stand still for a while it lessens but as soon as I load new chunks it kicks me. I tried comparing if it was just my world gen normally lagging upon a new world. Nope. I loaded a galacticraft dimension, Twilight forest, Deep dark nether and end, all 15 tps lowest. (I even do /forge tps do see MS as well). This massive lag spike primarily happens on the latest cauldron server with forge 1307 (http://sourceforge.net/projects/cauldron-unofficial/files/1.7.10-latest/) 

For some reason SSP is not as affected. It still lags for a while on (mystcraft 0.11.0.00 using forge 1307) but it still can create a new age and not lag after a while. 

When I try using the latest mystcraft on forge 1307 and the same version of cauldron, it crashes on world creation. Not on startup. Here is the crash report. I really hope it is not crashing because of outdated forge...if it is...is there any way I can find what is lagging the older version of mystcraft? Is it possible that one of my other mods is making it so slow? (Check crash report for mod list)

http://pastebin.com/40r3KH0S   (server crash report)

**Comment by XCompWiz** [comment] 2015-04-07 18:10
Yes, the latest versions won't work on Cauldron.  You'll need to get Cauldron to catch up on that one.
Can you try this with only Mystcraft and see how that fares?

You might also try binary searching to see if a singular mod is producing this effect (remove half the other mods, see if the problem persists, use the half with the problem).

**Comment by seantherobonaut** [comment] 2015-04-07 18:52
Will they not work on cauldron because of the version of forge, or another reason?

**Comment by seantherobonaut** [comment] 2015-04-08 16:16
Indeed it does. Which is really strange. As you mentioned it isn't as bad in SSP. Which leads me to believe it is something with cauldron. Which we both know it is near impossible to run a good server without. Instead of removing mystcraft entirely (because I love the mod) I will just disable the creation or use of Descriptive Books. I will add a custom recipe for crystals because I still want players to be able to use portals. It seems like a viable solution for now. 

Is there any way to get a descriptive book other than making it through a book binder? Can you find a descriptive book in dungeon chests?

Also with a custom recipe. I think an x of nether quarts and the rest with lapis is a good recipe for crystals for now? Or is that too easy? I mean finding crystals isn't that hard in mystcraft dimensions so no need to make crystals hard to craft right?

**Comment by XCompWiz** [comment] 2015-04-09 08:55
Closing as duplicate of #61

**Comment by XCompWiz** [comment] 2015-04-09 08:56
Errr. Read things wrong there. Anyway, I suspect it's because Cauldron is behind, yes, but it's also possible that Cauldron removed that field. They've done stranger. You'll have to take this to them regardless.

**Closed by XCompWiz** 2015-04-09 08:56 UTC

**Comment by Soundtoxin** [comment] 2015-04-12 21:33
@seantherobonaut Cauldron is up to Forge 1343 now and the issue still persists.

**Comment by XCompWiz** [comment] 2015-04-13 09:09
Then it would seem that Cauldron has removed that field or something similar.  Has an issue been created to report the issue to Cauldron?

**Comment by Soundtoxin** [comment] 2015-04-13 17:48
Due to the DMCA takedowns of Bukkit and Cauldron it is all very underground and I can't seem to find any way to report bugs to the Cauldron devs. I took the advice you gave on the issue I posted and got 0.11.0 (inital port of MystCraft to 1.7.10) from your Curse downloads page and it worked as you said. For now that's just what I'll use.

**Comment by Usverin** [comment] 2015-04-25 20:05
201 mods are working fine with cauldron, but not yours:( its absolutly sad, becouse you mod is the base mode and very interesting:(

**Comment by Prototik** [comment] 2015-05-02 15:12
Hey guys, I make working version of cauldron for latest version of mystcraft, you can grab it [here](https://prok.pw/cauldron-1.7.10-1.1395.1.0-installer.jar)

**Comment by Soundtoxin** [comment] 2015-05-03 03:41
Thanks, @Prototik. That's a newer version of Cauldron than I was able to find on the site where I usually get it. I think you can close this issue now @seantherobonaut.

**Comment by seantherobonaut** [comment] 2015-05-03 08:56
Ok @Soundtoxin ....WHERE THE HELL did you get an updated cauldron for Forge 1343...I WOULD VERY MUCH like to know.
I keep getting mine from here.
http://sourceforge.net/projects/cauldron-unofficial/files/1.7.10-latest/
