### ISSUE TITLE
"Baseline Profiling world unloaded before time!" logged incorrectly

### ISSUE THREAD

**Issue by nallar** [XCompWiz/Mystcraft-Issues#109] opened 2015-06-25 23:46 UTC
When any world unloads (not necessarily the profiling world), "Baseline Profiling world unloaded before time!" is logged.

`InstabilityDataCalculator.onWorldUnload` checks `running` before checking whether `dimId` matches with the world's dimension ID.

**Comment by XCompWiz** [comment] 2015-07-13 02:01
I'll double check this, but "before" isn't relevant given the way you phrased it. It should check both, and then order doesn't matter.

**Comment by XCompWiz** [comment] 2015-07-13 02:09
OK, checked the code and the issue is that it NEVER checks the dim id... *facepalm* Oops. I'll fix this when I next code.

**Comment by XCompWiz** [comment] 2015-07-13 14:25
Fixed for next release.

**Comment by Tomson124** [comment] 2015-07-25 11:08
I think you can close the issue @XCompWiz 
Bug is fixed for me :)

**Comment by XCompWiz** [comment] 2015-07-25 13:47
Thanks! :)

**Closed by XCompWiz** 2015-07-25 13:47 UTC
Labels: bug
