### ISSUE TITLE
Ran into a weird issue with this mod and crafttweaker on a server

### ISSUE THREAD

**Issue by Sunconure11** [XCompWiz/Mystcraft-Issues#241] opened 2018-05-25 13:44 UTC
https://pastebin.com/ZcVd4Dbz

I legitimately have no clue how the hell this even happened.

**Comment by Sunconure11** [comment] 2018-05-25 13:51
https://github.com/CraftTweaker/CraftTweaker/issues/553

**Comment by HellFirePvP** [comment] 2018-05-25 14:10
Duplicate of #236

**Closed** 2018-05-25 14:10 UTC
Labels: duplicate
