### ISSUE TITLE
Archivist villagers don't work properly on dedicated servers (GUI loading in the wrong order on the client)

### ISSUE THREAD

**Issue by KosmosPrime** [XCompWiz/Mystcraft-Issues#156] opened 2016-04-27 01:46 UTC
With Forge (10.13.4.1614) and when using Mystcraft (0.12.3.02) and NotEnoughItems (1.0.5.120) it is not possible to trade with an archivist villager on a dedicated server (works normally for integrated servers). If you right-click the villager, it will instead mess up your inventory until you reconnect. I have looked through the (NEI) source code but couldn't find any reason or obvious error. I don't think that happens for all custom villager UIs, so I'm reporting it here.

**Comment by KosmosPrime** [comment] 2016-05-05 15:40
I took a look at the log and noticed the phrase: "Gui handler 8 did not return a gui screen instance". I tried changing GuiHandlerVillager so that it prints out the entity and it's ID. It worked because (as I later found out) I loaded a singleplayer world before joining the server. The suspicion that the handlers were loaded in the wrong order was then confirmed because I made GuiHandlerManager not only print out the handler ID but also the class. This is the result: "Gui handler 8 (class com.xcompwiz.mystcraft.entity.EntityLinkbook$GuiHandlerBookEntity) did not return a gui screen instance".

**Comment by KosmosPrime** [comment] 2016-05-05 16:30
I did some more bytecode editing and produced a set of changed classes that you can copy into the mystcraft jar to fix the bug. Basically, I moved all the handler registering to GuiHandlerManager.<clinit> where they get placed into public static final fields that are then accessed by the handler classes and put into their private fields.
https://www.dropbox.com/s/npn52ekudyr5xty/CHANGES_mystcraft-1.7.10-0.12.3.02.zip?dl=1

**Comment by PsYcho-83** [comment] 2016-05-07 13:35
Hy @KosmosPrime ,
I have tried your changes and it seems to work ;) I just had to update my server and clients to 12.3.02 version ! Thanks :D

**Comment by Mochnant** [comment] 2016-06-05 18:05
I noticed this same bug.  Is there any word on an official fix?

**Comment by Eidelmaim** [comment] 2016-06-26 18:25
Hey KosmosPrime, is your fix a client side or server side or both? we have a glitch similar to this on our infinity server (dedicated server) which also results in a duplication of the players hot bar inventory. if this fix for the GUI is server side it might also stop the duplication since a GUI will now open.

this short 2 minute video shows how the duplication works

https://www.youtube.com/watch?v=_N8eCjUABIs&feature=youtu.be

**Comment by KosmosPrime** [comment] 2016-06-27 10:02
It's a problem in the code that can affect both server and client, but in my configuration the server didn't need the fix - only the client and only if you had NEI installed. However, if you have a mod which interfaces with mystcraft in some way then here's a possibility for the bug to occur.
It's dependent on the order in which the classes are loaded, if the client loads A before B and the server loads B before A (possibly because a class extends B) then the packedIDs are screwed up and you might be unable to trade with archivists, can't open book GUIs or something along those lines.

**Comment by XCompWiz** [comment] 2016-07-30 15:59
It's been a while since I dealt with any of this. Can you give me some point of reference for what needs to be fixed? :)
I recall some things about the GUI handlers, but are these my GUI handlers or the ones built into Forge?

**Comment by XCompWiz** [comment] 2016-07-30 17:46
Ah. I see the issue. Ya ,I'll have to restructure this.

Thanks for tracking it down and verifying the fix. :)

**Comment by XCompWiz** [comment] 2016-07-30 22:49
I've replaced my code to show GUIs with the newer integrated FML system.  That (plus the predefined ids via an enumeration) should fix most of the GUI issues.  Will be in the next release.

**Comment by Henri979** [comment] 2016-11-12 14:58
Hi there,
I am playing Infinity Evilved with Mystcraft (Version 0.12.3.02) and I expirence the same bug.
We are playing on a server (and I dont know what kind it is) with the version of FTB Infinity 2.6.0.
Is there an official solution for the bug?
And how do I fix it?

**Comment by Eidelmaim** [comment] 2016-11-13 15:03
i finally got around to testing this on my bukkit server, sorry this took so long, but i can confirm Mystcraft 1.7.10-0.12.3.03 resolves this issue.

@Henri979  you will need to update both your server AND all clients who play on your server to version 0.12.3.03

**Comment by XCompWiz** [comment] 2016-11-15 15:58
Thanks for verifying! :)

**Closed by XCompWiz** 2016-11-15 15:58 UTC
