### ISSUE TITLE
Sunrise colors are not the right direction.

### ISSUE THREAD

**Issue by keybounce** [XCompWiz/Mystcraft-Issues#276] opened 2018-07-08 17:25 UTC
I have an age with a sun rising in the east, and the sunrise colors in the south.

https://youtu.be/D3nQ3NAOZsw?t=1h22m4s

**Comment by XCompWiz** [comment] 2018-07-09 23:30
Duplicate of #242

**Closed by XCompWiz** 2018-07-09 23:30 UTC
