### ISSUE TITLE
Was told this was a Mystcraft Issue

### ISSUE THREAD

**Issue by O13SC3N3** [XCompWiz/Mystcraft-Issues#47] opened 2015-03-26 06:18 UTC
MC 1.7.10
Forge 1291 and LiteLoader
Java 8

Mystcraft Version 0.11.1.00

http://pastebin.com/U5W7Nmg1

**Comment by XCompWiz** [comment] 2015-03-26 10:48
Only indirectly. I'll be adding something to fix it, but the root cause seems to be that many mods feel it's perfectly acceptable to generate chunks far beyond the chunk they are decorating.
That's actually an issue, and causes a good deal of generation lag.
I'm not even sure what all is going on here, or how this set of logic even occurred.

**Comment by XCompWiz** [comment] 2015-03-26 11:02
Looking at the full logic flow here (we got vast majority of the callstack on this one. Nice. :D), it looks like cofh is forcing water to tick immediately during generation (which can easily cause cascading generation and other logic). The actual case here seems to be that a flower of some kind was broken by flowing water, resulting in a HarvestEvent. The issue caused a crash when something forced additional chunk generation inside the current population, which resulted in parallel generation, which Minecraft doesn't support in 1.7.10.
Looks like when the plant was broken a Lycanite mob was spawned.  It immediately started doing some collision detection things, which forced chunk population on the chunk it was in.

Normally, no (cascading) tick logic is run during actual generation, and for good reason.

**Comment by XCompWiz** [comment] 2015-03-28 12:30
I should clarify that it wasn't cofh causing this issue. It's just vanilla forcing tick logic to execute immediately when it generates small pools of water...  Ya, I don't get it either, and it's the only place in the code I can find that does that...

I'm going to close this issue. Not because it's fixed, but because this isn't any mod's fault.
I spent some time thinking about where the actual problem for this lay.  What particular issue caused the problem and how could we fix it?
The thing is, the only real failing here is vanilla generation and architecture. Nothing in that path was weird or unreasonable.  It all comes down to vanilla not supporting proper chunk generation.
Fortunately, I think this will be a rare occurence, as it hasn't happened otherwise.

**Closed by XCompWiz** 2015-03-28 12:30 UTC
