### ISSUE TITLE
Right clicking on a stack of unlinked link books does nothing.

### ISSUE THREAD

**Issue by keybounce** [XCompWiz/Mystcraft-Issues#275] opened 2018-07-08 07:14 UTC
In vanilla, if you have a stack of glass bottles, and right-click into water, each right-click will move one bottle into an empty inventory slot as a water bottle. Similarly, if you have a stack of blank maps, and right-click them, you will get maps for your current location.

In contrast, in Mystcraft, if you have a stack of unlinked link books, and right-click them, nothing happens.

https://youtu.be/D3nQ3NAOZsw?t=45m27s

**Comment by XCompWiz** [comment] 2018-07-11 11:13
Duplicate of #129

**Closed by XCompWiz** 2018-07-11 11:13 UTC
