### ISSUE TITLE
reload age after connection lost

### ISSUE THREAD

**Issue by quentfr21** [XCompWiz/Mystcraft-Issues#261] opened 2018-06-29 07:48 UTC
hello

i play on a offline mode server, if i leave (deco) in mystcraft worls when i re launch minecraft i'm stuck at the authentification the only way to login again is use tp if friend are present or a profile editor to change the dimension to the overworld

thanks again

**Comment by XCompWiz** [comment] 2018-07-01 23:35
Duplicate of #244 . Closing this one.

**Closed by XCompWiz** 2018-07-01 23:35 UTC
