### ISSUE TITLE
[1.12.2-0.13.4.03] Server crash on startup with craft tweaker and mod tweaker

### ISSUE THREAD

**Issue by Holtster2000** [XCompWiz/Mystcraft-Issues#250] opened 2018-06-03 14:14 UTC
the latest version of DireWolf20 1.12.2 SSP (+mystcraft and some other mods) launches but the server file (with forge version 14.23.3.2691 manually installed to match SSP instance) crashes on startup. When removing craft tweaker and mod tweaker the server launches normally.

Crash report:
https://pastebin.com/J7bmBRsp

**Comment by Alchemyy1** [comment] 2018-06-20 23:35
This is happening to me as well. I narrowed it down to crashing with tinker io installed.

**Comment by XCompWiz** [comment] 2018-07-01 20:55
Looks like an issue with fluid symbol generation. Specifically, Mystcraft asks a fluid block for the meta state at which is it full, and then asks for the block state for that meta. Seems in this case that the resultant blockstate is either null or otherwise weird.
Will need more investigation, but I can add some null catching for the next build at least.

**Comment by XCompWiz** [comment] 2018-07-01 22:43
Duplicate of #245

**Closed by XCompWiz** 2018-07-01 22:43 UTC
