### ISSUE TITLE
Mystcraft & BOP -> crash in new world (SSP)

### ISSUE THREAD

**Issue by Bogdan-G** [XCompWiz/Mystcraft-Issues#94] opened 2015-06-07 21:18 UTC
Hello. Im use: MC 1.7.10; Forge 1428; Fastcraft 1.22ctest8; Optifine U_B7; CCC; NEI; etc
Mystcraft 0.11.11.00 & BiomesOPlenty 2.1.0.1283.
No LiteLoader, no Opis.

Create new world -> fly in creative ~5min -> detected biome [Birch Forest] and crash:
crash-report - https://gist.github.com/Bogdan-G/04b7d57a303d74b5e1e2
full-fml-log - https://raw.githubusercontent.com/Bogdan-G/Fileware/a0e6a8a8b4317a51ba1fbfc968be8b4e38f8a700/logs/local/fml-client-latest_225552.log

**Comment by xJon** [comment] 2015-06-08 13:48
I have a similar crash report: http://pastebin.com/FKKU6A5j
Forge 1420, Fastcraft 1.21, no Optifine.

**Comment by XCompWiz** [comment] 2015-06-08 19:31
xJon, that's a completely different crash report. Please create a new issue for it. :)

Bogdan-G, definitely a hard one here.
If you try removing BOP, does it stop happening?
Do you have any mods which pre-gens chunks?

I note that you have a lot of leaking worlds right before the crash.  It's possible that they are related.  Unfortunately it's difficult to determine why they are leaking and what's going on there.

Can you try the "binary search" method to determine which mods cause the leaking worlds?

I don't wish to point any fingers, and this is a rough guess, but I'd start with removing the GraveStone mod, as that's doing something with world loading and generation at startup and might be keeping references.

**Comment by Bogdan-G** [comment] 2015-06-09 23:52
Will describe that done, a message will be complementary. 
Steps:
1) 1 run
a) Update mods: gravestone up to 2.12.4; binnie-mods up to pre10; BloodMagic up to 1.3.3-4; NEIIntegration up to 1.0.10;
b) reduce spawn+generate in gravestone, lycanitesmobs, botania; off gen in a few worlds GT and down gen GTores;
c) run -Dfastcraft.debug.fwel
world type BOP+UBC,, enter new gen world, craft workbench, wood plank, survival game, run 5 min ->
https://gist.github.com/Bogdan-G/f0d7edd079455d853637 - SSP server terminated and close game.
I understand the world mystcraft generates in the villages only or something else? I saw a black sphere and waila showed what they mystcraft.
https://raw.githubusercontent.com/Bogdan-G/Fileware/a0f66d193dce8d8647f06c40277deb905fbe9998/logs/local/fml-client-latest_0233.log - full-fml-log
hmm...
`exterminatorJeff.undergroundBiomes.worldGen.*`
`cpw.mods.fml.common.eventhandler.ASMEventHandler_514_UndergroundBiomes_onOreGenerate_Post.*`
>Exception caught during firing event net.minecraftforge.event.terraingen.OreGenEvent$Post@5abb7bed

mystcraft no ore-gen o_o
At some stage there is no verification, and is an exception. In mod Twilight Forest was a problem with the decorations(already decoration) of the other mods and their intersection, he decided it as something.

**Comment by sfPlayer1** [comment] 2015-06-14 23:38
https://github.com/Bogdan-G/Fileware/blob/master/logs/date/140615-3/crash-2015-06-14_23.59.58-server.txt shows the issue better, as it has FC's biome monitoring feature enabled, which is designed to help debugging this kind of issue.

The primary issue is in ChunkProviderMyst.chunkExists. It'll always return true, which will in turn cause chunk decoration to happen right away, even if the surrounding chunks aren't generated yet. Accessing the surrounding chunks from a decorator hook causes reentrant decoration, as that'll run from provideChunk right away likewise.

The decoration code isn't reentrant-safe, you may have to use at least 3x3 patches like I do in IC2 and decorate only the center. The implementation of chunkExists must not unconditionally return true of course.

Note that a similar issue exist with broken decorator implementations on top of the vanilla chunk provider. If they access anything outside the safe 3x3 region, they may load chunks that started to fulfil the neighbor presence criterion. This causes them to decorate as well, leading to the same "already decorating" problems, but typically much rarer.

**Comment by XCompWiz** [comment] 2015-06-16 22:11
That explains a lot.  Seems that that function didn't used to be used on the actual chunk providers, just the high level ones (ex. server chunk provider).  I can probably fix this. Thanks, Player!

**Comment by XCompWiz** [comment] 2015-07-13 19:11
Coming back to this, that CANNOT (or, at least, SHOULD NOT) be the issue. ChunkProviderGenerate does the exact same thing.  The chunkExists function should not be called except on the higher level provider (ChunkProviderServer). As far as I can tell, nothing calls the method on the lower level logic.

There is not a reasonable way for the lower level logic to know what chunks are loaded/saved/previously generated without asking the higher level one, and it shouldn't do that.
Now, the biggest issue here is the reuse of the interface for two levels of logic, but I can't fix the flawed abstraction.

So the fix for this is NOT to change chunkExists.  Especially since vanilla doesn't make that error (from what I can tell). It's got to be something else.

I've added a bit of code to detect if that function is ever called. It isn't in vanilla. We'll get a stacktrace if it ever is.

@Bogdan-G Have you tried this without Mo'Creatures?  I saw some entities spawn in there, and they might have triggered further decoration...

**Comment by sfPlayer1** [comment] 2015-07-13 20:54
Hmm I tend to agree after another look, IC2's scanning code just works significantly different. The valid area to query is actually only 2x2 chunks towards +x+z, which MOC and many other mods don't ensure. I'm tempted to make this more resistant against incorrect use...

**Comment by Bogdan-G** [comment] 2015-07-22 18:03
Sorry that is not answered, the sea was.
@XCompWiz Mod MpC creates the essence of vanilla as well as in the new chunk, but its probably during the pre-gen. Config MoC mod default(+fix because it works without CustomMobSpawner(CMS broken TwilightForest spawn and random entities off )
Ok, I udpate Mystcraft and del MoC, test in progress.

**Comment by Bogdan-G** [comment] 2015-08-01 19:38
Return, I updated mods/libs/forge, is now a list: http://i.imgur.com/lKKsE4B.png

Run 1: The test with the MoC, go in the game, fly to creative, 10-15 minutes after the crash. When you run this FPS has become more stable when the flow of sounds down (sounds did not have any music, and the same). 
https://github.com/Bogdan-G/Fileware/tree/master/logs/date/010815-1

Run 2: Test without the MoC, rendering the game became faster by 15% in the beginning, and then during the flight originally hung in the game for 5 minutes and did not answer when dropped and I flew another 5-15 minutes, and then crash again. SRP file server(/csampler) number 5, I could not be created because it was created at the time of the accident.
https://github.com/Bogdan-G/Fileware/tree/master/logs/date/010815-2

**Comment by XCompWiz** [comment] 2015-08-06 02:49
This looks like it's just something caused by Spawned Animals (or FastCraft)...

I wonder if you can replicate this in the Overworld...
Try the latest version of Mystcraft as well. Some code I was testing snuck into the build. I meant to be testing if it prevented scenarios like this.

**Comment by Bogdan-G** [comment] 2015-08-06 15:19
Run:
1) Update mods: http://i.imgur.com/0ViYP2N.png and mystcraft.
2) Start game, 4 attempts(two of them a memory leak) - fails, 5 attempt normal start, java.exe ~3gb
3) create world - 2 attemps - fails(memory leaks, busy all heap, leak in save DIM0), reloads game, 3 attempt - overworld create, pause, enter game, wait ~5-8 min (fps 1-20) CPU 80%, wait ~6min (fps 1-6) CPU 30%, fly in creative (1-110fps, yeah, not stable), constantly I hear the sound of the repair tool, made several SRP,
later, the world is no longer generated chunks, all entity no move, only animated, server tps 1-4, fps client 60-90, I waited ~10 minutes, and started leaking memory and the game no longer signs of life. I waited another ~10 minutes, but the game does not come to life and I closed it through the Windows Task Manager.

Some screenshots: 
A) scr F2 game: http://imgur.com/a/KdHtl
1 - a place where no longer go generation;  2 and 3 - during the flight;  4 - place spawn to create the world
B) scr button PrtScr: http://imgur.com/a/dIZtn
logs: https://github.com/Bogdan-G/Fileware/tree/master/logs/date/060815-2

**Comment by XCompWiz** [comment] 2015-08-10 10:45
If there is lag that's another issue. For this issue (ticket) I only care about if it crashes with the original issue.
Memory leaks and lag issues should be brought up separately, and you should attempt to determine which mod is causing them.

**Comment by Mysteryem** [comment] 2015-09-11 22:50
I've been building a custom modpack and I seem to be having this issue or at least one very similar, I hadn't noticed it at first as I had been progressively adding more mods and only being in-game for a few minutes to ensure that it didn't instantly crash. The crash only seems to occur quite a few minutes into the profiling.

I've tried with and without fastcraft, with and without fastcraft's config option to monitor biome decorators and I disabled Underground Biomes Constructs from interacting by adding the Mystcraft dummy dimension's ID to UBC's dimension blacklist (added to blacklist after the 3rd crash report below by the looks of things).

https://gist.github.com/Mysteryem/d24496672ccd07b12cb0 (no fastcraft)
https://gist.github.com/Mysteryem/8f5d043f950129f0c6d9 (no fastcraft)
https://gist.github.com/Mysteryem/7fd440d41e5c53f8152d (fastcraft)
https://gist.github.com/Mysteryem/c74d238ba684eaa52e07 (fastcraft)
https://gist.github.com/Mysteryem/67b390b97ce6070f4af4 (fastcraft)
https://gist.github.com/Mysteryem/7afd3895b04571e5f56e (fastcraft)

I'd first thought it might be something to do with the 'Mutated', 'M' biomes, but the most recent crash shows that Birch Forest Hills threw an error while populating. Interestingly, all but the 3rd crash have BlockLiquid and BlockDynamicLiquid in the stack traces.

I also have a couple of earlier crashes that may or may not be related:
https://gist.github.com/Mysteryem/c7cc31602223ecb57db7 (no fastcraft)
https://gist.github.com/Mysteryem/a4193bf0150fb4319f67 (fastcraft)

I will have a go at removing mods to see if I can find the cause tomorrow. Thankfully, I can compare the mods currently in my modpack with those of Bogdan-G's to produce this list of mods which are shared amongst both our packs https://gist.github.com/Mysteryem/15797bd3faf16c15e8ca

**Comment by Mysteryem** [comment] 2015-09-12 23:29
Ok, the issue has been resolved in a pre-release build of Underground Biomes Constructs https://www.dropbox.com/s/zn0b7qbafvdx2p3/UndergroundBiomesConstructs-1.7.2-test42.jar?dl=0

For reference, this seems to have been a conflict between Biomes O' Plenty and UBC. I would guess that Mystcraft was merely highlighting the issue. (crash was reproducible with the only mods being UBC, BOP and Mystcraft)

**Comment by XCompWiz** [comment] 2015-09-15 10:04
Mystcraft often seems to end up highlighting issues in other mods; sometimes issues that wouldn't have come up otherwise or are otherwise difficult to run into.

Glad it has been resolved! Hopefully the fix will move out of pre-release soon. :)

**Closed by XCompWiz** 2015-09-15 10:04 UTC
