### ISSUE TITLE
Duplicating item and related crash

### ISSUE THREAD

**Issue by DreamThorn** [XCompWiz/Mystcraft-Issues#190] opened 2017-07-24 11:26 UTC
I placed the book binder successfully, but it remained in my hotbar.  So I placed it again, next to the first one to see what happens.  It placed again, but I thought that it could cause crashes, so I removed it, but this led it to create a pickup.  Picking it up caused the game to crash, and it now also always crashes when trying to load that world.

**Comment by heldplayer** [comment] 2017-07-24 12:34
Curious, trying this in the latest version and cannot reproduce. Are you playing with other mods and if so, could you provide a modlist?

A crash log would also be nice, if you could put it up on [pastebin](https://pastebin.com/) or in a [gist](https://gist.github.com/).

**Comment by DreamThorn** [comment] 2017-07-24 12:47
I'll get the crash log when I'm back home.  Also, this was on the second most recent version of Mystcraft, but the change log doesn't address it, so I assume it's still there.

Meanwhile, here is the mod list:

Mystcraft
Botania
Immersive Engineering
Biomes o' Plenty
Spice of Life
Optifine
AppleSkin
AppleCore
Baubles

I think that's all of them.  I'll also check this when back home.

**Comment by DreamThorn** [comment] 2017-07-25 07:45
[crash-2017-07-19_20.18.23-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/1172351/crash-2017-07-19_20.18.23-server.txt)
[crash-2017-07-19_20.19.52-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/1172350/crash-2017-07-19_20.19.52-server.txt)

**Comment by DreamThorn** [comment] 2017-07-25 07:49
So, I guess Biomes O' Plenty is causing the crash by not checking whether the object has a "down" variant when doing some kind of achievement detection calculation.

**Comment by AFoxygen** [comment] 2017-07-30 13:27
I had a similar issue. Crash after placing book binder. I didn't notice if it was duplicated in my hotbar, but when i opened (and then closed) my inventory, another book binder was thrown, and then the game crashed. Tried to load it today and it crashed before spawning in.
[crash-2017-07-29_14.33.19-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/1185700/crash-2017-07-29_14.33.19-server.txt)
[crash-2017-07-30_09.08.05-server.txt](https://github.com/XCompWiz/Mystcraft-Issues/files/1185699/crash-2017-07-30_09.08.05-server.txt)

**Comment by heldplayer** [comment] 2017-07-30 13:47
Looks like a faulty implementation of getStateFromMeta on Mystcraft's side.
Mystcraft uses the block meta to store the facing of the book binder, however it uses all possible EnumFacing values to calculate the meta instead of only the ones that are allowed.

Biomes O' Plenty is triggering the crash, because it is trying to get a block state from the item stack based on its meta, and the stack has a meta of 0 which corresponds to EnumFacing.DOWN.

A solution would be checking the input meta and only looking at the bits that are required for the facing (and not using an extra bit for DOWN and UP which aren't used, in the process).

**Comment by HellFirePvP** [comment] 2017-07-30 19:28
Yes it is a faulty implementation on the bookbinder as serialization/deserialization wasn't handled properly. Will scan for the other blocks aswell, however the bookbinder-related serialization/deserialization will be fixed in the next release.

**Closed** 2017-07-31 07:58 UTC
Labels: fixed in next release
