### ISSUE TITLE
[0.11.12.00] Crash with bspkrsCore 6.16

### ISSUE THREAD

**Issue by allout58** [XCompWiz/Mystcraft-Issues#101] opened 2015-06-16 18:02 UTC
As soon as the main menu shows, the game crashes. Disabling bspkrsCore allows the game to start up and run the Mystcraft profiler. After the initial profiling, I was able to reenable bspkrsCore without problems.
The entities rendered by bspkrsCore on the main menu were rendered then froze immediately. Several seconds passed with the game frozen, then crashed.

Crashlog: https://gist.github.com/allout58/34d70465ee9b1fb59ac0

**Comment by XCompWiz** [comment] 2015-06-16 22:07
Bravo for determining the cause. I had to run it in debug mode in Eclipse to find this.

I actually made notes on the change log on how to handle this.  You can simply disable just the main menu mobs and then everything proceeds smoothly.
The issue isn't really easy to fix except through bspkrsCore.  I know exactly what's happening and have a fix, but I've not looked to see if the code is open source and modifiable. If it is, I can make a PR to fix it.  I've already spoken with bspkrs about it.

Thanks!  I'll leave this open until the problem is resolved.

**Comment by XCompWiz** [comment] 2015-07-13 18:35
I'm adding "wontfix" to this so I'll stop looking at it. :P I'd appreciate it if someone would let me know when or if @bspkrs has fixed this. I know he's already moved to 1.8, so I wouldn't expect a fix at this point.

**Comment by Bogdan-G** [comment] 2015-08-02 12:44
bspkrs he said that ate you fail, turn off the rendering in the main menu mobs.

**Closed** 2017-07-24 12:00 UTC
Labels: bug, other mod, wontfix
